/* =====================================================================
   PathFinder India — Data
   Sources: NTA, CBSE, UGC, AICTE, NMC, BCI, ICAI, ICSI, NIFT, NID,
            NCVET, DGT (ITI), MoE, NDA, NEET-UG handbook (2024-25 cycle).
   Salary ranges: AmbitionBox & Naukri medians for fresh graduates (2024-25).
   ===================================================================== */

const STREAMS = [
  {
    id: "science-pcm",
    icon: "🔬",
    color: "#22d3ee",
    name: "Science — PCM",
    tagline: "Physics, Chemistry, Mathematics. The gateway to engineering, architecture, defence and pure sciences.",
    chips: ["Engineering", "Architecture", "Defence", "Pure Science", "Data/AI"],
    subjects: ["Physics", "Chemistry", "Mathematics", "English", "Optional (CS/PE/Biology)"],
    duration: "Class 11–12 (2 years)",
    bestFor: "Students strong in logic, problem-solving and abstract reasoning.",
    leadsTo: ["B.Tech / B.E.", "B.Arch", "B.Sc. (Physics, Math, CS, Statistics)", "NDA → Defence", "Integrated M.Sc.", "BS Research (IISc / IISERs)"],
    topExams: ["JEE Main", "JEE Advanced", "BITSAT", "VITEEE", "NATA", "NDA", "CUET-UG"],
    pros: ["Widest course choice (can switch to commerce/arts later)", "High-paying STEM careers", "Eligible for almost every UG entrance"],
    cons: ["Very competitive entrance exams", "Heavy syllabus in Class 11–12", "Coaching costs can be high"],
    avgSalary: "₹4–25 LPA (entry, varies by college)",
  },
  {
    id: "science-pcb",
    icon: "🧬",
    color: "#34d399",
    name: "Science — PCB",
    tagline: "Physics, Chemistry, Biology. The path to medicine, dentistry, biotech and life sciences.",
    chips: ["MBBS", "BDS", "Pharmacy", "Nursing", "AYUSH", "Biotech"],
    subjects: ["Physics", "Chemistry", "Biology", "English", "Optional (PE/Psychology)"],
    duration: "Class 11–12 (2 years)",
    bestFor: "Students fascinated by living systems, healthcare and research.",
    leadsTo: ["MBBS", "BDS", "BAMS / BHMS / BUMS", "B.Pharm", "B.Sc. Nursing", "B.Sc. (Bio, Biotech, Microbio, Zoology)", "B.V.Sc (Veterinary)", "B.Sc. Agriculture"],
    topExams: ["NEET-UG", "AIIMS (via NEET)", "ICAR AIEEA (Agri)", "CUET-UG"],
    pros: ["Stable, respected healthcare careers", "Strong global demand", "Government job opportunities"],
    cons: ["NEET is highly competitive (~24 lakh aspirants)", "MBBS takes 5.5 years + PG", "Limited switch to engineering without Math"],
    avgSalary: "₹6–15 LPA (MBBS post-internship); ₹3–6 LPA (allied health)",
  },
  {
    id: "science-pcmb",
    icon: "⚗️",
    color: "#a78bfa",
    name: "Science — PCMB",
    tagline: "All five: Physics, Chemistry, Maths, Biology. Choose PCM, PCB, or keep both paths open.",
    chips: ["PCM", "PCB", "Engineering", "Medical", "Research", "Biotech"],
    subjects: ["Physics", "Chemistry", "Mathematics", "Biology", "English"],
    duration: "Class 11–12 (2 years)",
    bestFor: "Undecided high-achievers who want both NEET and JEE on the table.",
    leadsTo: ["Engineering or Medicine", "Biotech / Bioinformatics", "B.Sc. (any)", "Pharmacy"],
    topExams: ["NEET-UG", "JEE Main", "CUET-UG"],
    pros: ["Maximum career flexibility", "Eligible for both NEET and JEE", "Strong base for interdisciplinary fields"],
    cons: ["Workload is significantly heavier", "Hard to excel at both NEET + JEE", "Not offered by every school"],
    avgSalary: "Depends on chosen track",
  },
  {
    id: "commerce",
    icon: "💼",
    color: "#f59e0b",
    name: "Commerce",
    tagline: "Accounts, Business, Economics. The route to finance, management, law and entrepreneurship.",
    chips: ["CA", "CS", "BBA", "B.Com", "Banking", "Economics"],
    subjects: ["Accountancy", "Business Studies", "Economics", "English", "Math / IP / Applied Math (optional)"],
    duration: "Class 11–12 (2 years)",
    bestFor: "Students who enjoy numbers, business news, and decision-making.",
    leadsTo: ["B.Com (Hons)", "BBA / BMS", "CA / CS / CMA", "BBA-LLB", "B.A. Economics", "Actuarial Science", "Hotel Management"],
    topExams: ["CUET-UG", "IPMAT (IIM Indore/Rohtak)", "CA Foundation", "CS CSEET", "NPAT", "DU JAT (now via CUET)"],
    pros: ["Lower entrance-exam pressure than Science", "Clear professional ladders (CA/CS/CMA)", "Strong job market in BFSI"],
    cons: ["Without Math, some top BBA/Eco programs are closed", "CA pass percentage is ~10–15%", "Salary growth depends heavily on specialisation"],
    avgSalary: "₹3–12 LPA (entry); CA freshers ₹8–12 LPA",
  },
  {
    id: "arts",
    icon: "🎨",
    color: "#ec4899",
    name: "Arts / Humanities",
    tagline: "From history to psychology to political science — the foundation for law, media, civil services and creative careers.",
    chips: ["Law", "UPSC", "Journalism", "Psychology", "Design", "Sociology"],
    subjects: ["History", "Pol. Science", "Geography", "Economics", "Psychology", "Sociology", "Languages", "Fine Arts"],
    duration: "Class 11–12 (2 years)",
    bestFor: "Students who love reading, writing, debating, and understanding people & society.",
    leadsTo: ["BA (Hons)", "BA-LLB (Integrated Law)", "BJMC (Journalism)", "BFA (Fine Arts)", "B.Des", "Hotel Management", "B.El.Ed (Teaching)"],
    topExams: ["CUET-UG", "CLAT", "AILET", "IPMAT", "NIFT / NID", "UCEED", "Christ / Symbiosis entrances"],
    pros: ["Lower textbook load — more analytical work", "Excellent for UPSC / Judiciary aspirants", "Creative & flexible careers"],
    cons: ["Still stigmatised in some communities", "Initial salaries can be modest", "Career path needs more self-direction"],
    avgSalary: "₹3–10 LPA (entry); Law/UPSC much higher with experience",
  },
  {
    id: "diploma",
    icon: "🛠️",
    color: "#7c5cff",
    name: "Diploma (Polytechnic)",
    tagline: "3-year technical diploma directly after 10th. Lateral entry into 2nd year of B.Tech.",
    chips: ["Mechanical", "Civil", "Electrical", "Computer Sci", "Electronics"],
    subjects: ["Branch-specific (Mech / Civil / EE / ECE / CS / Auto)"],
    duration: "3 years (full-time)",
    bestFor: "Students who want to start earning early or jump into B.Tech via lateral entry.",
    leadsTo: ["Junior Engineer / Technician jobs", "Lateral entry to B.E. / B.Tech (2nd year)", "AMIE", "Government PSU technician roles"],
    topExams: ["State polytechnic CETs (JEECUP-UP, DTE-MH, AP-POLYCET, etc.)", "Lateral Entry JEE for B.Tech"],
    pros: ["Skip Class 11–12 if you're sure", "Cheaper than B.Tech", "Faster route to a job"],
    cons: ["Salary ceiling lower than B.Tech", "Some companies still prefer degree holders", "Switching streams later is hard"],
    avgSalary: "₹1.8–4 LPA (diploma); ₹4–8 LPA after lateral B.Tech",
  },
  {
    id: "iti",
    icon: "🔧",
    color: "#fb923c",
    name: "ITI / Vocational",
    tagline: "Skill-based trade training (6 months to 2 years) recognised by DGT/NCVET.",
    chips: ["Electrician", "Fitter", "Welder", "COPA", "Plumber", "AC Mechanic"],
    subjects: ["Trade-specific (one of 130+ NCVT trades)"],
    duration: "6 months to 2 years",
    bestFor: "Students wanting fast employment in skilled trades, MSMEs, or self-employment.",
    leadsTo: ["Apprenticeship (NAPS)", "Industrial jobs", "Self-employment", "Diploma via lateral entry (in some states)"],
    topExams: ["State ITI admission (merit-based on 10th marks)", "AITT (final certification by NCVT)"],
    pros: ["Quickest path to earning", "Low fees (gov. ITIs nearly free)", "Skills always in demand"],
    cons: ["Lower starting salary", "Career growth needs upskilling", "Limited corporate ladder"],
    avgSalary: "₹1.2–3 LPA (entry); rises with experience and Gulf placements",
  },
  {
    id: "paramedical",
    icon: "🩺",
    color: "#10b981",
    name: "Paramedical (after 10th)",
    tagline: "Short diploma / certificate healthcare courses you can join straight after Class 10.",
    chips: ["DMLT", "X-Ray Tech", "OT Tech", "Nursing (GNM)", "Dental Hygienist"],
    subjects: ["Anatomy, Physiology, Pathology, Lab Tech (course-specific)"],
    duration: "1–3 years",
    bestFor: "Biology-inclined students wanting fast entry into healthcare without NEET.",
    leadsTo: ["Lab technician", "Radiology assistant", "Operation theatre asst.", "Auxiliary Nursing & Midwifery", "Further B.Sc. lateral entry"],
    topExams: ["State paramedical CETs", "Direct admission via 10th marks"],
    pros: ["No NEET needed", "Healthcare jobs in big demand", "Short duration, fast ROI"],
    cons: ["Cannot become a doctor through this route", "Recognition varies — verify NCVET / state council", "Salary lower than MBBS"],
    avgSalary: "₹1.8–4.5 LPA (entry)",
  },
];

const COURSES = [
  // SCIENCE PCM
  {
    id: "btech",
    name: "B.Tech / B.E.",
    stream: "science-pcm",
    duration: "4 years",
    durBucket: "mid",
    entrance: "yes",
    exams: ["JEE Main", "JEE Advanced", "BITSAT", "VITEEE", "SRMJEE", "MET", "WBJEE", "MHT-CET", "KCET"],
    eligibility: "Class 12 with PCM, ≥ 50–75% (varies)",
    fees: "₹0.4–4 lakh/year (IITs/NITs cheaper than private)",
    colleges: ["IITs (23)", "NITs (31)", "IIITs (26)", "BITS Pilani", "DTU & NSUT", "VIT", "Manipal"],
    careers: ["Software Engineer", "Mechanical Engineer", "Electrical Engineer", "Civil Engineer", "Data Scientist", "Product Manager"],
    salary: "₹6–25 LPA (placement medians at top colleges)",
    desc: "Four-year undergraduate engineering degree. Most popular branches: CSE/AI/ML, ECE, Mechanical, Civil, Electrical, Chemical.",
    pros: ["Highest-paid UG track for top colleges", "Global mobility", "Strong alumni networks at IITs/NITs"],
    cons: ["Top colleges need ~99 percentile JEE", "Quality varies wildly across 4,000+ colleges", "Coaching adds significant cost"],
  },
  {
    id: "barch",
    name: "B.Arch",
    stream: "science-pcm",
    duration: "5 years",
    durBucket: "long",
    entrance: "yes",
    exams: ["NATA", "JEE Main Paper 2"],
    eligibility: "Class 12 with PCM, ≥ 50%",
    fees: "₹1.5–5 lakh/year",
    colleges: ["SPA Delhi/Bhopal/Vijayawada", "IIT Roorkee/Kharagpur", "CEPT Ahmedabad", "NIT Calicut/Trichy", "Sir JJ College Mumbai"],
    careers: ["Architect", "Urban Planner", "Interior Designer", "Landscape Architect"],
    salary: "₹3.5–8 LPA (entry); much higher with own practice",
    desc: "Five-year professional architecture degree. Council of Architecture (COA) registration mandatory to practice.",
    pros: ["Creative + technical hybrid", "Self-employment possible", "Global recognition of Indian B.Arch"],
    cons: ["5 years is long", "Modest starting salary", "Real estate market dependent"],
  },
  {
    id: "bsc-pcm",
    name: "B.Sc. (Physics / Maths / CS / Stats)",
    stream: "science-pcm",
    duration: "3 years (4 with research as per NEP)",
    durBucket: "mid",
    entrance: "yes",
    exams: ["CUET-UG", "IISER Aptitude Test", "NEST", "ISI Admission Test"],
    eligibility: "Class 12 with PCM, ≥ 50–60%",
    fees: "₹10k–80k/year (public); up to ₹3 lakh/year (private)",
    colleges: ["St. Stephen's & Hindu College DU", "St. Xavier's Mumbai/Kolkata", "IISc (BS Research)", "IISERs (7)", "Presidency Kolkata"],
    careers: ["Research Scientist", "Data Analyst", "Statistician", "Quant Analyst", "Teacher / Professor"],
    salary: "₹3–8 LPA (entry); ₹15+ LPA in quant/data",
    desc: "Foundational science degree. NEP 2020 allows a 4-year B.Sc. (Research) leading directly to PhD eligibility.",
    pros: ["Best base for research & PhD", "Higher studies abroad easier", "Cheaper than B.Tech"],
    cons: ["Lower starting salary than B.Tech", "Job market favours PG holders", "Lab infrastructure varies"],
  },

  // SCIENCE PCB
  {
    id: "mbbs",
    name: "MBBS",
    stream: "science-pcb",
    duration: "5.5 years (4.5 + 1 yr internship)",
    durBucket: "long",
    entrance: "yes",
    exams: ["NEET-UG"],
    eligibility: "Class 12 with PCB, ≥ 50% (40% reserved); NEET qualified",
    fees: "₹6k–25k/year (govt.); ₹10–25 lakh/year (private)",
    colleges: ["AIIMS Delhi & 21 new AIIMS", "MAMC, JIPMER", "CMC Vellore", "AFMC Pune", "KGMU Lucknow", "BHU IMS"],
    careers: ["Doctor (Physician)", "Surgeon (post-MS)", "Specialist (post-MD)", "Public Health Officer"],
    salary: "₹6–12 LPA (post-internship); ₹15–60 LPA after PG/specialisation",
    desc: "The standard Indian medical degree, regulated by the National Medical Commission (NMC). One unified entry: NEET-UG.",
    pros: ["Highly respected profession", "Stable, recession-proof", "Strong government job pipeline"],
    cons: ["NEET is brutally competitive", "Long study + PG bottleneck", "High private college fees"],
  },
  {
    id: "bds",
    name: "BDS (Dental)",
    stream: "science-pcb",
    duration: "5 years (4 + 1 yr internship)",
    durBucket: "long",
    entrance: "yes",
    exams: ["NEET-UG"],
    eligibility: "Class 12 with PCB, ≥ 50%; NEET qualified",
    fees: "₹20k–1 lakh/year (govt.); ₹3–8 lakh/year (private)",
    colleges: ["Maulana Azad Institute of Dental Sciences", "Govt. Dental College Mumbai", "King George's Medical Univ.", "Manipal College of Dental Sciences"],
    careers: ["Dentist", "Orthodontist (post-MDS)", "Oral Surgeon", "Dental Researcher"],
    salary: "₹3–6 LPA (entry); much higher in private practice",
    desc: "Bachelor of Dental Surgery — backup for many NEET aspirants and a strong standalone career via private practice.",
    pros: ["Strong self-employment route", "Shorter than MBBS", "Growing cosmetic-dentistry market"],
    cons: ["Saturation in metros", "Setup cost for own clinic is high", "Lower entry salary than MBBS"],
  },
  {
    id: "ayush",
    name: "BAMS / BHMS / BUMS / BSMS",
    stream: "science-pcb",
    duration: "5.5 years",
    durBucket: "long",
    entrance: "yes",
    exams: ["NEET-UG"],
    eligibility: "Class 12 with PCB, ≥ 50%; NEET qualified",
    fees: "₹15k–1.5 lakh/year (govt.); ₹2–6 lakh/year (private)",
    colleges: ["IMS BHU (Ayurveda)", "NIA Jaipur", "Govt. Ayurvedic College Tripunithura", "NIH Kolkata (Homeopathy)"],
    careers: ["Ayurvedic / Homeopathic Doctor", "Researcher", "AYUSH Wellness Centre"],
    salary: "₹3–6 LPA (entry); private practice scales higher",
    desc: "AYUSH = Ayurveda, Yoga, Unani, Siddha, Homeopathy. Regulated by NCISM/NCH. NEET-UG is the single entry exam.",
    pros: ["Lower NEET cutoffs than MBBS", "Govt. push for AYUSH (Ministry of AYUSH)", "Growing global wellness market"],
    cons: ["Lower social prestige vs MBBS", "Limited allopathic prescription rights", "Regional acceptance varies"],
  },
  {
    id: "bpharm",
    name: "B.Pharm",
    stream: "science-pcb",
    duration: "4 years",
    durBucket: "mid",
    entrance: "yes",
    exams: ["GPAT (PG)", "WBJEE Pharmacy", "MHT-CET", "State CETs"],
    eligibility: "Class 12 with PCB or PCM, ≥ 50%",
    fees: "₹40k–2 lakh/year",
    colleges: ["NIPER Mohali", "Jamia Hamdard", "BITS Pilani", "ICT Mumbai", "Manipal College of Pharmacy"],
    careers: ["Pharmacist", "Drug Inspector", "R&D Pharma Scientist", "Medical Representative", "Regulatory Affairs"],
    salary: "₹3–7 LPA (entry)",
    desc: "Pharmacy degree regulated by the Pharmacy Council of India (PCI). Required to register as a pharmacist.",
    pros: ["Steady jobs in India's $50B+ pharma industry", "Govt. + private opportunities", "Pathway to Pharm.D / research"],
    cons: ["Modest entry salary in retail pharmacy", "Career growth needs PG", "Long study hours"],
  },
  {
    id: "bsc-nursing",
    name: "B.Sc. Nursing",
    stream: "science-pcb",
    duration: "4 years",
    durBucket: "mid",
    entrance: "yes",
    exams: ["AIIMS Nursing", "JIPMER Nursing", "PGIMER", "State Nursing CETs"],
    eligibility: "Class 12 with PCB, ≥ 45–50%",
    fees: "₹20k–1.5 lakh/year",
    colleges: ["AIIMS Delhi", "CMC Vellore", "RAK College of Nursing", "AFMC Pune"],
    careers: ["Registered Nurse", "ICU/OT Specialist", "Nurse Practitioner", "Hospital Administrator"],
    salary: "₹3–6 LPA in India; ₹15–40 LPA abroad (UK/Gulf/Canada)",
    desc: "Regulated by the Indian Nursing Council. High global demand makes nursing one of India's strongest export-of-skill careers.",
    pros: ["Excellent global demand", "Stable, respected", "Quick to abroad migration"],
    cons: ["Demanding shifts", "Lower base salary in India", "Physically taxing role"],
  },
  {
    id: "bvsc",
    name: "B.V.Sc & A.H. (Veterinary)",
    stream: "science-pcb",
    duration: "5.5 years",
    durBucket: "long",
    entrance: "yes",
    exams: ["NEET-UG (15% AIQ via VCI)", "State Veterinary CETs"],
    eligibility: "Class 12 with PCB, ≥ 50%",
    fees: "₹15k–80k/year (govt.)",
    colleges: ["IVRI Bareilly", "TANUVAS Chennai", "GADVASU Ludhiana", "WBUAFS Kolkata"],
    careers: ["Veterinary Doctor", "Livestock Officer", "Wildlife Veterinarian", "Dairy/Poultry Industry"],
    salary: "₹4–8 LPA (entry)",
    desc: "Veterinary Council of India (VCI) regulated. 15% All India Quota seats filled via NEET-UG.",
    pros: ["Underserved field — low competition", "Govt. jobs available", "Niche specialisations (wildlife, exotic pets)"],
    cons: ["Awareness still low", "Lab infra varies", "Field work in remote areas"],
  },

  // COMMERCE
  {
    id: "bcom",
    name: "B.Com (Hons / Pass)",
    stream: "commerce",
    duration: "3–4 years",
    durBucket: "mid",
    entrance: "yes",
    exams: ["CUET-UG", "NPAT", "Christ Univ Entrance", "Symbiosis SET"],
    eligibility: "Class 12 (any stream, Commerce preferred), ≥ 50–60%",
    fees: "₹10k–2 lakh/year",
    colleges: ["SRCC Delhi", "Hindu College DU", "Hansraj DU", "St. Xavier's Mumbai/Kolkata", "Loyola Chennai", "Christ Bangalore"],
    careers: ["Accountant", "Tax Consultant", "Banker", "Financial Analyst", "Audit Associate"],
    salary: "₹3–8 LPA (entry); CA/CFA-qualified ₹10+ LPA",
    desc: "India's most-enrolled UG degree. Best paired with a professional qualification (CA, CS, CMA, CFA, ACCA).",
    pros: ["Low entry barrier", "Versatile foundation", "Stackable with CA/CFA/MBA"],
    cons: ["Plain B.Com salaries are modest", "Crowded job market", "Career outcomes depend on add-ons"],
  },
  {
    id: "bba",
    name: "BBA / BMS",
    stream: "commerce",
    duration: "3 years",
    durBucket: "mid",
    entrance: "yes",
    exams: ["IPMAT (5-yr integrated)", "NPAT", "SET", "CUET-UG", "Christ Entrance", "DU JAT (CUET now)"],
    eligibility: "Class 12 any stream, ≥ 50–60% (Math preferred for IPMAT)",
    fees: "₹40k–4 lakh/year",
    colleges: ["IIM Indore IPM", "IIM Rohtak IPM", "Shaheed Sukhdev DU", "NMIMS Mumbai", "Christ Bangalore", "Symbiosis Pune"],
    careers: ["Business Analyst", "Marketing Executive", "HR Associate", "Operations Manager", "Entrepreneur"],
    salary: "₹4–12 LPA (top BBA); ₹3–5 LPA (average)",
    desc: "Bachelor of Business Administration. Top route: IPMAT → 5-yr integrated MBA at IIM Indore/Rohtak.",
    pros: ["Practical business curriculum", "Internship-heavy", "Direct ladder to MBA / corporate"],
    cons: ["Quality very college-dependent", "Average BBA salaries < B.Com+CA", "Theory-heavy at weaker colleges"],
  },
  {
    id: "ca",
    name: "Chartered Accountancy (CA)",
    stream: "commerce",
    duration: "4.5–5 years (after 12th)",
    durBucket: "long",
    entrance: "yes",
    exams: ["CA Foundation → Intermediate → Final (ICAI)"],
    eligibility: "Class 12 (any stream); register with ICAI",
    fees: "₹80k–1.5 lakh (total ICAI fees)",
    colleges: ["ICAI (Institute of Chartered Accountants of India) — single body"],
    careers: ["Chartered Accountant", "Auditor", "Tax Advisor", "CFO", "Forensic Accountant"],
    salary: "₹8–12 LPA (freshers, India); ₹20+ LPA (Big 4 partners)",
    desc: "India's apex finance qualification. 3-tier ICAI exams (Foundation, Intermediate, Final) + 2-year articleship.",
    pros: ["High respect & earning ceiling", "Self-employment possible", "Very low course fee vs ROI"],
    cons: ["Pass rate ~10–15% at Final level", "Long, gruelling articleship", "Plateau without specialisation"],
  },
  {
    id: "cs",
    name: "Company Secretary (CS)",
    stream: "commerce",
    duration: "3–4 years",
    durBucket: "mid",
    entrance: "yes",
    exams: ["CSEET → Executive → Professional (ICSI)"],
    eligibility: "Class 12 any stream",
    fees: "₹50k–1 lakh (total)",
    colleges: ["ICSI (Institute of Company Secretaries of India)"],
    careers: ["Company Secretary", "Corporate Legal Advisor", "Compliance Officer"],
    salary: "₹4–8 LPA (entry); ₹15+ LPA in listed companies",
    desc: "Statutory officer in every listed Indian company. ICSI is the regulating body.",
    pros: ["Mandatory role under Companies Act 2013", "Niche, less crowded than CA", "Good corporate ladder"],
    cons: ["Lower brand vs CA", "Slower salary growth in early years", "Heavy law-focused syllabus"],
  },
  {
    id: "cma",
    name: "Cost & Management Accountant (CMA)",
    stream: "commerce",
    duration: "3–4 years",
    durBucket: "mid",
    entrance: "yes",
    exams: ["CMA Foundation → Intermediate → Final (ICMAI)"],
    eligibility: "Class 12 any stream",
    fees: "₹60k–1 lakh (total)",
    colleges: ["ICMAI (Institute of Cost Accountants of India)"],
    careers: ["Cost Accountant", "Management Accountant", "Internal Auditor", "FP&A Analyst"],
    salary: "₹5–9 LPA (entry)",
    desc: "Specialises in cost accounting, budgeting and management accounting — strong in manufacturing / PSUs.",
    pros: ["Demand in manufacturing & PSUs", "Recognised in 50+ countries (CIMA tie-up)", "Cheaper than MBA"],
    cons: ["Less popular than CA", "Pass rates low at Final level", "Brand value still building"],
  },
  {
    id: "actuarial",
    name: "Actuarial Science",
    stream: "commerce",
    duration: "6–10 years",
    durBucket: "long",
    entrance: "yes",
    exams: ["ACET (Institute of Actuaries of India)"],
    eligibility: "Class 12 with Math, ≥ 85%",
    fees: "₹2–5 lakh (total, exam-by-exam)",
    colleges: ["Institute of Actuaries of India (IAI)", "B.Sc. Actuarial — Amity, NMIMS"],
    careers: ["Actuary", "Risk Analyst", "Pricing Analyst (Insurance)", "Pension Consultant"],
    salary: "₹8–15 LPA (entry); ₹25+ LPA fully qualified",
    desc: "Tiny but lucrative profession (~600 qualified actuaries in India). Requires clearing 13 IAI exams.",
    pros: ["Extreme scarcity → very high pay", "Global mobility (UK FIA recognition)", "Pure math + finance role"],
    cons: ["Multi-year exam grind (low pass rates)", "Few colleges teach it formally", "Niche industry (mostly insurance)"],
  },

  // ARTS
  {
    id: "ba-hons",
    name: "BA (Hons) — Eco / Pol Sci / Psych / English / History",
    stream: "arts",
    duration: "3–4 years",
    durBucket: "mid",
    entrance: "yes",
    exams: ["CUET-UG", "JMI Entrance", "Christ Entrance"],
    eligibility: "Class 12 any stream, ≥ 50–60% (Math required for Eco)",
    fees: "₹10k–2 lakh/year",
    colleges: ["St. Stephen's DU", "LSR DU", "Hindu DU", "JMI", "Presidency Kolkata", "Ashoka", "Azim Premji Univ"],
    careers: ["Civil Servant (UPSC)", "Journalist", "Policy Analyst", "Researcher", "Psychologist", "Content Strategist"],
    salary: "₹3–8 LPA (entry); UPSC ₹56k+ pm basic for IAS Probationer",
    desc: "Three-year (four with research under NEP) honours degree. Eco (Hons) requires Class 12 Math; Psychology is the fastest-growing.",
    pros: ["Strong base for UPSC, law, MBA", "Lower entry barrier than STEM", "Develops critical thinking"],
    cons: ["Plain BA salaries modest", "Outcome depends heavily on college", "Higher studies often essential"],
  },
  {
    id: "ballb",
    name: "BA-LLB (Integrated Law)",
    stream: "arts",
    duration: "5 years",
    durBucket: "long",
    entrance: "yes",
    exams: ["CLAT", "AILET (NLU Delhi)", "LSAT-India", "MH-CET Law", "SLAT"],
    eligibility: "Class 12 any stream, ≥ 45–50%",
    fees: "₹2.5–5 lakh/year (NLUs); ₹3–10 lakh/year (private)",
    colleges: ["NLSIU Bangalore", "NALSAR Hyderabad", "NLU Delhi", "WBNUJS Kolkata", "Symbiosis Law Pune", "Jindal Global Law"],
    careers: ["Lawyer / Advocate", "Corporate Counsel", "Judge (post-Judicial Services)", "Legal Researcher"],
    salary: "₹10–18 LPA (top tier-1 firms); ₹4–7 LPA (mid-tier)",
    desc: "Bar Council of India (BCI) regulated. 5-yr integrated degrees from National Law Universities are the gold standard.",
    pros: ["Strong job market in corporate law", "Pathway to Judiciary & UPSC", "Self-practice possible"],
    cons: ["CLAT cutoffs are very high", "Bar Exam needed to practice", "Long grind to senior advocate"],
  },
  {
    id: "bjmc",
    name: "BJMC / BMM (Journalism & Mass Comm)",
    stream: "arts",
    duration: "3 years",
    durBucket: "mid",
    entrance: "yes",
    exams: ["CUET-UG", "IIMC Entrance (PG)", "Symbiosis SET"],
    eligibility: "Class 12 any stream, ≥ 50%",
    fees: "₹40k–3 lakh/year",
    colleges: ["IIMC Delhi (PG)", "Symbiosis SIMC", "Xavier Institute of Comm. Mumbai", "ACJ Chennai", "Christ Bangalore"],
    careers: ["Journalist", "News Anchor", "PR Executive", "Content Creator", "Digital Marketer", "Film Director"],
    salary: "₹3–7 LPA (entry); top anchors / creators much higher",
    desc: "Covers print, broadcast, digital media and PR. Internships during the course are decisive for placements.",
    pros: ["Creative, dynamic field", "Strong digital media boom", "Multiple career exits (PR, marketing, film)"],
    cons: ["Modest starting pay in print/TV", "Demanding work hours", "Job security weaker than govt. roles"],
  },
  {
    id: "bdes",
    name: "B.Des (Design)",
    stream: "arts",
    duration: "4 years",
    durBucket: "mid",
    entrance: "yes",
    exams: ["UCEED (IITs)", "NID DAT", "NIFT Entrance", "Pearl Academy Entrance", "SEED (Symbiosis)"],
    eligibility: "Class 12 any stream, ≥ 50%",
    fees: "₹2–6 lakh/year",
    colleges: ["NID Ahmedabad", "IIT Bombay IDC", "IIT Guwahati Design", "NIFT (16 centres)", "Pearl Academy", "Srishti Bangalore"],
    careers: ["UX/UI Designer", "Product Designer", "Animator", "Graphic Designer", "Game Designer", "Furniture Designer"],
    salary: "₹5–15 LPA (entry, top design colleges)",
    desc: "Four-year design degree across product, communication, UX, animation and game design. NID/IIT-IDC are flagship.",
    pros: ["High demand in tech (UX/UI)", "Creative + lucrative hybrid", "Global freelance market"],
    cons: ["Studio fees can be very high", "Portfolio matters more than marks", "NID/UCEED very competitive"],
  },
  {
    id: "bfa",
    name: "BFA (Bachelor of Fine Arts)",
    stream: "arts",
    duration: "4 years",
    durBucket: "mid",
    entrance: "yes",
    exams: ["College-specific entrance + portfolio (BHU, JMI, MSU Baroda, etc.)"],
    eligibility: "Class 12 any stream, ≥ 50%",
    fees: "₹15k–2 lakh/year",
    colleges: ["Sir JJ School of Art Mumbai", "Faculty of Fine Arts MSU Baroda", "BHU Faculty of Visual Arts", "Govt. College of Fine Arts Chennai"],
    careers: ["Painter / Sculptor", "Illustrator", "Art Director", "Conservator", "Art Teacher"],
    salary: "₹2.5–5 LPA (entry); commissions & gallery sales much higher",
    desc: "For students with serious studio talent — painting, sculpture, applied art, printmaking, art history.",
    pros: ["Pure creative path", "Self-employment & gallery route", "Low fees in govt. colleges"],
    cons: ["Unpredictable income early on", "Few corporate jobs", "Requires self-marketing"],
  },
  {
    id: "bhm",
    name: "BHM / BHMCT (Hotel Management)",
    stream: "arts",
    duration: "3–4 years",
    durBucket: "mid",
    entrance: "yes",
    exams: ["NCHMCT JEE", "IIHM eCHAT", "AIMA UGAT", "State CETs"],
    eligibility: "Class 12 any stream with English, ≥ 50%",
    fees: "₹80k–3 lakh/year",
    colleges: ["IHM Pusa Delhi", "IHM Mumbai/Bangalore/Chennai", "WGSHA Manipal", "IIHM Kolkata", "Oberoi STEP"],
    careers: ["Hotel Manager", "Chef", "F&B Manager", "Cruise Liner Crew", "Event Manager", "Airline Crew"],
    salary: "₹3–6 LPA (India entry); ₹15+ LPA on cruise/Gulf",
    desc: "Hospitality degree opening doors in hotels, airlines, cruise lines, QSR chains and event management.",
    pros: ["Strong global mobility", "Visible career growth in hotels", "Practical, hands-on curriculum"],
    cons: ["Demanding shifts & low entry pay", "Service-industry burnout common", "Growth slow in mid-management"],
  },

  // DEFENCE
  {
    id: "nda",
    name: "NDA → Indian Armed Forces",
    stream: "science-pcm",
    duration: "3 yrs NDA + 1 yr academy training",
    durBucket: "mid",
    entrance: "yes",
    exams: ["NDA (UPSC) — twice a year"],
    eligibility: "Unmarried, 16.5–19.5 yrs, Class 12 PCM (Air Force/Navy) or any stream (Army)",
    fees: "Fully government-funded (stipend during training)",
    colleges: ["National Defence Academy, Khadakwasla", "IMA Dehradun / INA Ezhimala / AFA Hyderabad (post-NDA)"],
    careers: ["Officer in Army / Navy / Air Force"],
    salary: "₹56,100+ pm (Lieutenant) + allowances, free housing, lifetime pension",
    desc: "Tri-services academy. Two written attempts per year via UPSC. Followed by SSB interview (5-day assessment).",
    pros: ["Free, fully-funded officer training", "Lifetime pension & benefits", "Respect & adventure"],
    cons: ["Strict physical & medical standards", "Demanding lifestyle", "Limited geographic choice in postings"],
  },

  // DIPLOMA
  {
    id: "polytechnic",
    name: "Diploma (Polytechnic)",
    stream: "diploma",
    duration: "3 years",
    durBucket: "mid",
    entrance: "yes",
    exams: ["JEECUP (UP)", "DTE-Maharashtra", "AP/TS POLYCET", "Karnataka DCET", "Delhi CET"],
    eligibility: "Class 10 passed with 35–50% (state-specific)",
    fees: "₹5k–40k/year (govt.); ₹40k–1 lakh/year (private)",
    colleges: ["Govt. Polytechnic Mumbai/Delhi/Pune/Bangalore", "MSBTE-affiliated colleges", "Pusa Polytechnic Delhi"],
    careers: ["Junior Engineer", "Site Supervisor", "PSU Technician", "Lateral B.Tech entry"],
    salary: "₹1.8–4 LPA (diploma); ₹5–8 LPA after lateral B.Tech",
    desc: "Three-year AICTE-approved technical diploma. Lateral entry directly to 2nd year B.E./B.Tech via state lateral CETs.",
    pros: ["Start technical career at 18", "Cheaper than B.Tech", "Path to B.Tech still open"],
    cons: ["Lower starting salaries", "Less brand-name than degree colleges", "Switching to non-tech is hard"],
  },

  // ITI / VOCATIONAL
  {
    id: "iti-trade",
    name: "ITI Trade Certificate (NCVT)",
    stream: "iti",
    duration: "6 months – 2 years",
    durBucket: "short",
    entrance: "no",
    exams: ["Merit-based admission via state ITI portals; AITT for final certification"],
    eligibility: "Class 8 or 10 passed (trade-specific)",
    fees: "₹0–10k/year (govt.); ₹20k–60k (private)",
    colleges: ["Govt. ITIs (~15,000)", "Private ITIs (~14,000)", "NSTI (National Skill Training Institutes)"],
    careers: ["Electrician", "Fitter", "Welder", "COPA Operator", "Plumber", "Mechanic"],
    salary: "₹1.2–3 LPA (India entry); ₹4–8 LPA in Gulf with experience",
    desc: "NCVT/SCVT-certified trade courses across 130+ trades. NAPS apprenticeships offered after ITI.",
    pros: ["Fastest path to a paying job", "Skills universally in demand", "Low fees, strong govt. push (Skill India)"],
    cons: ["Lower lifetime earning ceiling", "Manual / shift work", "Quality of private ITIs varies"],
  },

  // PARAMEDICAL
  {
    id: "dmlt",
    name: "DMLT (Medical Lab Technology)",
    stream: "paramedical",
    duration: "2 years",
    durBucket: "short",
    entrance: "no",
    exams: ["Direct admission via 10th marks; some states have CETs"],
    eligibility: "Class 10 passed (Science preferred)",
    fees: "₹30k–1.5 lakh (total)",
    colleges: ["AIIMS Paramedical", "PGIMER Chandigarh", "AIIPMR Mumbai", "State paramedical councils"],
    careers: ["Pathology Lab Technician", "Hospital Lab In-charge", "Blood Bank Technician"],
    salary: "₹1.8–3.5 LPA (entry)",
    desc: "Two-year diploma to operate clinical pathology, biochemistry and microbiology labs.",
    pros: ["Quick healthcare entry", "Steady hospital demand", "Bridge to B.Sc. MLT"],
    cons: ["Repetitive, lab-bound work", "Limited growth without B.Sc.", "Regulation varies by state"],
  },
  {
    id: "gnm",
    name: "GNM (General Nursing & Midwifery)",
    stream: "paramedical",
    duration: "3 years + 6 months internship",
    durBucket: "mid",
    entrance: "yes",
    exams: ["State Nursing CETs; many institutes admit on 10+2 marks"],
    eligibility: "Class 12 (any stream, Science preferred), ≥ 40–50%",
    fees: "₹30k–1.5 lakh/year",
    colleges: ["AIIMS School of Nursing", "RAK College", "Christian Medical College Vellore", "State nursing colleges"],
    careers: ["Registered Nurse", "Midwife", "Community Health Worker"],
    salary: "₹2.5–5 LPA (India); ₹15+ LPA abroad",
    desc: "Diploma-level nursing programme. Registered with State Nursing Council & Indian Nursing Council.",
    pros: ["Strong abroad demand", "Lower fees than B.Sc. Nursing", "Govt. hospitals hire heavily"],
    cons: ["B.Sc. Nursing is preferred for senior roles", "Shift work", "Career ceiling without bridge programs"],
  },
];

const EXAMS = [
  { name: "JEE Main", category: "science", body: "NTA", when: "January & April (twice a year)", for: "B.Tech / B.E. / B.Arch / B.Plan at NITs, IIITs, GFTIs, & qualifier for JEE Advanced.", desc: "India's largest engineering entrance — ~12 lakh candidates per session." },
  { name: "JEE Advanced", category: "science", body: "IIT (rotating)", when: "May", for: "Admission to 23 IITs.", desc: "Top ~2.5 lakh JEE Main scorers qualify. Single hardest UG exam in India." },
  { name: "NEET-UG", category: "science", body: "NTA", when: "May (once a year)", for: "MBBS, BDS, BAMS/BHMS/BUMS, BVSc, B.Sc. Nursing.", desc: "Sole medical entrance under NMC. ~24 lakh aspirants in 2024." },
  { name: "BITSAT", category: "science", body: "BITS Pilani", when: "May–June", for: "B.E. at BITS Pilani, Goa, Hyderabad campuses.", desc: "Computer-based test; highly competitive for CSE." },
  { name: "VITEEE", category: "science", body: "VIT", when: "April", for: "B.Tech at VIT Vellore, Chennai, AP, Bhopal.", desc: "Multi-attempt window over 5 days." },
  { name: "NATA", category: "science", body: "Council of Architecture", when: "April / July (multiple)", for: "B.Arch admissions (with JEE Main Paper 2).", desc: "Tests drawing aptitude, mathematics & general aesthetic sensitivity." },
  { name: "CUET-UG", category: "uni", body: "NTA", when: "May–June", for: "Central / State / Deemed Universities — DU, JNU, JMI, BHU, AMU, etc.", desc: "Replaces traditional college cutoffs for 250+ universities since 2022." },
  { name: "CLAT", category: "arts", body: "Consortium of NLUs", when: "December", for: "5-year integrated BA-LLB at 22 NLUs (except NLU Delhi).", desc: "150 MCQs in 2 hrs covering English, GK, Legal Reasoning, Logical Reasoning, Quant." },
  { name: "AILET", category: "arts", body: "NLU Delhi", when: "December", for: "BA-LLB at NLU Delhi.", desc: "Separate from CLAT; ~120 BA-LLB seats." },
  { name: "IPMAT", category: "commerce", body: "IIM Indore / IIM Rohtak", when: "May", for: "5-year integrated MBA at IIM Indore & Rohtak.", desc: "Aptitude + Verbal Ability + WAT/PI." },
  { name: "NPAT", category: "commerce", body: "NMIMS", when: "January–May", for: "BBA, B.Com (Hons), BTech at NMIMS schools.", desc: "Multi-window booking; relatively accessible." },
  { name: "CA Foundation", category: "commerce", body: "ICAI", when: "May & November (twice a year)", for: "Entry to the CA Course.", desc: "Open after Class 12; written exam in 4 papers." },
  { name: "CS CSEET", category: "commerce", body: "ICSI", when: "January, May, July, November", for: "Entry to CS Executive Programme.", desc: "Computer-based; quarterly attempts." },
  { name: "ACET", category: "commerce", body: "Institute of Actuaries of India", when: "May & December", for: "Entry to Actuarial Science.", desc: "Three-hour online; tests math, stats, English." },
  { name: "NDA", category: "defence", body: "UPSC", when: "April & September (twice a year)", for: "Officer entry to NDA Khadakwasla.", desc: "Written + SSB Interview + Medical. Open from 16.5 yrs of age." },
  { name: "NID DAT", category: "design", body: "NID Ahmedabad", when: "January (Prelims) + May (Mains)", for: "B.Des at NID campuses.", desc: "Tests visualisation, creativity, hand skills, materials sense." },
  { name: "NIFT Entrance", category: "design", body: "NIFT", when: "February", for: "B.Des / B.F.Tech at 16 NIFT campuses.", desc: "CAT, GAT, Situation Test for design candidates." },
  { name: "UCEED", category: "design", body: "IIT Bombay", when: "January", for: "B.Des at IIT Bombay, Guwahati, Hyderabad, IIITDM.", desc: "Visualisation & spatial ability heavy." },
  { name: "NCHMCT JEE", category: "arts", body: "NTA", when: "May", for: "BHM/BHMCT at 21 IHMs.", desc: "Computer-based; tests numerical, reasoning, English, aptitude for hospitality, GK." },
  { name: "ICAR AIEEA", category: "science", body: "NTA", when: "July", for: "B.Sc. Agriculture / Horticulture / Forestry at 75+ ICAR universities.", desc: "Single window for Agri universities." },
  { name: "AIIMS Nursing", category: "science", body: "AIIMS", when: "June", for: "B.Sc. Nursing at AIIMS.", desc: "Highly competitive; ~75 seats at AIIMS Delhi." },
  { name: "JEECUP", category: "science", body: "JEECUP UP", when: "April–May", for: "Polytechnic admissions in Uttar Pradesh.", desc: "Largest state polytechnic entrance." },
  { name: "DTE Maharashtra", category: "science", body: "DTE Maharashtra", when: "June", for: "Polytechnic diploma admissions in MH.", desc: "Centralised Admission Process (CAP) post Class 10." },
  { name: "SET (Symbiosis)", category: "commerce", body: "Symbiosis Intl Univ", when: "May", for: "BBA, BBA-LLB, BA Mass Comm at Symbiosis colleges.", desc: "150 questions; followed by WAT-PI." },
  { name: "Christ University Entrance", category: "arts", body: "Christ Univ Bangalore", when: "March–May", for: "BBA, BA, B.Com, Psychology programs at Christ.", desc: "Selection: written test + skill assessment + interview." },
];

const CAREERS = [
  { role: "Software Engineer", qual: "B.Tech CSE / B.Sc. CS + coding", salary: "6–25 LPA", stream: "Science PCM" },
  { role: "Data Scientist", qual: "B.Tech + ML / B.Sc. Stats + PG", salary: "8–22 LPA", stream: "Science PCM" },
  { role: "Mechanical Engineer", qual: "B.Tech Mechanical", salary: "4–10 LPA", stream: "Science PCM" },
  { role: "Civil Engineer", qual: "B.Tech / Diploma Civil", salary: "3.5–8 LPA", stream: "Science PCM" },
  { role: "Architect", qual: "B.Arch + COA reg.", salary: "3.5–8 LPA", stream: "Science PCM" },
  { role: "Doctor (MBBS)", qual: "MBBS via NEET", salary: "8–15 LPA", stream: "Science PCB" },
  { role: "Dentist", qual: "BDS via NEET", salary: "3–6 LPA", stream: "Science PCB" },
  { role: "Pharmacist", qual: "B.Pharm + PCI reg.", salary: "3–7 LPA", stream: "Science PCB" },
  { role: "Veterinary Doctor", qual: "B.V.Sc & A.H.", salary: "4–8 LPA", stream: "Science PCB" },
  { role: "Nurse", qual: "B.Sc. / GNM Nursing", salary: "3–6 LPA (India)", stream: "Science PCB" },
  { role: "Physiotherapist", qual: "BPT (4.5 yrs)", salary: "3–6 LPA", stream: "Science PCB" },
  { role: "Chartered Accountant", qual: "CA via ICAI", salary: "8–12 LPA", stream: "Commerce" },
  { role: "Company Secretary", qual: "CS via ICSI", salary: "4–8 LPA", stream: "Commerce" },
  { role: "Investment Banker", qual: "BBA/B.Com + MBA / CFA", salary: "12–30 LPA", stream: "Commerce" },
  { role: "Actuary", qual: "ACET → IAI Fellowship", salary: "8–25 LPA", stream: "Commerce" },
  { role: "Bank PO", qual: "Any graduate + IBPS/SBI PO", salary: "8–12 LPA", stream: "Commerce" },
  { role: "Stock Broker", qual: "B.Com + NISM certifications", salary: "4–15 LPA", stream: "Commerce" },
  { role: "Lawyer", qual: "BA-LLB + Bar Exam", salary: "5–18 LPA", stream: "Arts / Commerce" },
  { role: "Civil Servant (IAS/IPS)", qual: "Any graduate + UPSC CSE", salary: "₹56k pm + perks", stream: "Any" },
  { role: "Journalist", qual: "BJMC / BA + experience", salary: "3–7 LPA", stream: "Arts" },
  { role: "Clinical Psychologist", qual: "BA Psych + M.Phil Clinical Psych", salary: "4–8 LPA", stream: "Arts (Science PCB also)" },
  { role: "UX / UI Designer", qual: "B.Des / Self-taught + portfolio", salary: "6–18 LPA", stream: "Design / Any" },
  { role: "Graphic Designer", qual: "B.Des / BFA / Diploma", salary: "3–8 LPA", stream: "Design / Arts" },
  { role: "Fashion Designer", qual: "B.Des (NIFT/NID)", salary: "4–10 LPA", stream: "Design / Arts" },
  { role: "Animator / VFX Artist", qual: "B.Des / Diploma in Animation", salary: "4–12 LPA", stream: "Design / Arts" },
  { role: "Chef", qual: "BHM + culinary diploma", salary: "3–10 LPA", stream: "Hotel Mgmt" },
  { role: "Hotel Manager", qual: "BHM / IHM diploma", salary: "4–10 LPA", stream: "Hotel Mgmt" },
  { role: "Air Cabin Crew", qual: "Class 12 + Aviation training", salary: "5–12 LPA", stream: "Any" },
  { role: "Commercial Pilot", qual: "CPL (DGCA approved)", salary: "12–80 LPA", stream: "Science PCM" },
  { role: "Indian Army / Navy / Air Force Officer", qual: "NDA / CDS / AFCAT", salary: "₹56k+ pm + perks", stream: "PCM / Any" },
  { role: "Merchant Navy Officer", qual: "B.Sc. Nautical Science / DNS", salary: "8–40 LPA (USD-denominated)", stream: "Science PCM" },
  { role: "Game Developer", qual: "B.Tech / B.Des + Unity/Unreal", salary: "6–18 LPA", stream: "Science / Design" },
  { role: "Digital Marketer", qual: "Any graduate + certifications", salary: "4–12 LPA", stream: "Any" },
  { role: "School Teacher", qual: "B.A./B.Sc. + B.Ed. + CTET", salary: "3–7 LPA", stream: "Any" },
  { role: "Entrepreneur / Founder", qual: "No formal requirement", salary: "Variable", stream: "Any" },
  { role: "Research Scientist", qual: "B.Sc. → M.Sc. → PhD", salary: "6–15 LPA", stream: "Science" },
  { role: "Forensic Scientist", qual: "B.Sc. Forensic Sci + PG", salary: "4–8 LPA", stream: "Science PCB" },
  { role: "Biotechnologist", qual: "B.Tech / B.Sc. Biotech", salary: "4–8 LPA", stream: "Science (PCB/PCMB)" },
  { role: "Environmental Scientist", qual: "B.Sc. Env Sci + PG", salary: "4–8 LPA", stream: "Science" },
  { role: "Chartered Engineer (PSU)", qual: "B.Tech + GATE", salary: "8–18 LPA", stream: "Science PCM" },
  { role: "Electrician (ITI)", qual: "ITI Electrician + apprenticeship", salary: "1.8–4 LPA", stream: "ITI" },
  { role: "Welder / Fitter", qual: "ITI Welder / Fitter", salary: "1.8–4 LPA (India); higher in Gulf", stream: "ITI" },
];

const QUIZ = [
  {
    q: "Which kind of problem excites you the most?",
    opts: [
      { text: "Solving a tricky math or physics puzzle", w: { pcm: 3, pcmb: 2 } },
      { text: "Diagnosing why a person is unwell", w: { pcb: 3, pcmb: 2, paramedical: 2 } },
      { text: "Spotting why a business is losing money", w: { commerce: 3 } },
      { text: "Arguing why a law is unfair", w: { arts: 3 } },
      { text: "Designing a poster or app", w: { design: 3, arts: 1 } },
      { text: "Fixing something with your hands", w: { iti: 3, diploma: 2 } },
    ],
  },
  {
    q: "Pick a school subject you secretly enjoy.",
    opts: [
      { text: "Mathematics", w: { pcm: 3, commerce: 1, pcmb: 1 } },
      { text: "Biology", w: { pcb: 3, paramedical: 2, pcmb: 1 } },
      { text: "Accountancy or Economics", w: { commerce: 3 } },
      { text: "History / Civics / Languages", w: { arts: 3 } },
      { text: "Art / Drawing / Craft", w: { design: 3, arts: 2 } },
      { text: "Workshop / Computer practicals", w: { iti: 2, diploma: 3, pcm: 1 } },
    ],
  },
  {
    q: "How comfortable are you with high-stakes exams (JEE / NEET)?",
    opts: [
      { text: "Bring it on — I love competition", w: { pcm: 2, pcb: 2, pcmb: 2 } },
      { text: "Will study hard but want options", w: { pcm: 2, commerce: 1, arts: 1 } },
      { text: "Prefer skill or portfolio over exams", w: { design: 3, arts: 2, iti: 2 } },
      { text: "Want to start earning quickly", w: { iti: 3, diploma: 2, paramedical: 2 } },
    ],
  },
  {
    q: "What does a great work day look like to you?",
    opts: [
      { text: "Coding or designing systems on a laptop", w: { pcm: 3, design: 2 } },
      { text: "Helping a patient feel better", w: { pcb: 3, paramedical: 2 } },
      { text: "Closing a deal or balancing books", w: { commerce: 3 } },
      { text: "Writing, speaking, or shaping policy", w: { arts: 3 } },
      { text: "Sketching ideas and making prototypes", w: { design: 3 } },
      { text: "Working on a machine or site", w: { iti: 3, diploma: 2 } },
    ],
  },
  {
    q: "Where do you want to be 8 years from now?",
    opts: [
      { text: "Engineer at a top tech / R&D firm", w: { pcm: 3 } },
      { text: "Practising doctor or healthcare specialist", w: { pcb: 3 } },
      { text: "CA / Investment banker / Entrepreneur", w: { commerce: 3 } },
      { text: "IAS / Lawyer / Journalist / Professor", w: { arts: 3 } },
      { text: "Lead designer at a creative studio", w: { design: 3 } },
      { text: "Skilled technician with own workshop", w: { iti: 3, diploma: 2 } },
    ],
  },
  {
    q: "How important is starting salary vs long-term passion?",
    opts: [
      { text: "Starting salary matters most", w: { pcm: 3, commerce: 2, paramedical: 1 } },
      { text: "Balance of both", w: { pcm: 1, pcb: 1, commerce: 2, arts: 1, design: 1 } },
      { text: "Passion above all", w: { arts: 3, design: 3, pcb: 1 } },
      { text: "Job security & quick employment", w: { iti: 3, diploma: 2, paramedical: 2 } },
    ],
  },
  {
    q: "Math — your honest feeling?",
    opts: [
      { text: "Love it, top scorer", w: { pcm: 3, commerce: 1 } },
      { text: "Comfortable, not a fan", w: { commerce: 2, pcb: 1, arts: 1 } },
      { text: "Would rather avoid", w: { arts: 3, design: 2, paramedical: 1 } },
      { text: "Indifferent — give me practical math", w: { iti: 2, diploma: 2, commerce: 1 } },
    ],
  },
  {
    q: "Your dream learning environment?",
    opts: [
      { text: "Lab / engineering campus", w: { pcm: 3, pcmb: 1 } },
      { text: "Hospital / biology lab", w: { pcb: 3, paramedical: 2 } },
      { text: "Trading floor / boardroom", w: { commerce: 3 } },
      { text: "Library / courtroom / newsroom", w: { arts: 3 } },
      { text: "Design studio / makerspace", w: { design: 3 } },
      { text: "Workshop / job site", w: { iti: 3, diploma: 2 } },
    ],
  },
];

const FAQ = [
  {
    q: "Can I switch streams after Class 10 if I change my mind?",
    a: "Yes, but with restrictions. Switching from Science to Commerce or Arts is generally easy at the start of Class 11; switching INTO Science (especially PCM/PCB) after Class 11 is often not allowed because of subject prerequisites. Some boards allow a re-admission to Class 11 if you’re flexible about losing a year.",
  },
  {
    q: "Do I have to take Math in Commerce?",
    a: "No, but it changes your options. Without Class 12 Math you cannot pursue Economics (Hons), most BBA programs at IIM-IPM / SRCC / DU, B.Sc. Statistics, or Actuarial Science. CA, CS, CMA and B.Com Pass do not require Math.",
  },
  {
    q: "Is a diploma (polytechnic) inferior to a B.Tech?",
    a: "It is shorter (3 years vs 4) and starts at a lower salary, but you can do lateral entry directly into the 2nd year of B.Tech via state lateral CETs. Net time becomes 3+3 = 6 years vs 2+4 = 6 years through 11–12 + B.Tech, so the path is equivalent in years.",
  },
  {
    q: "Is NEET the only way to become a doctor in India?",
    a: "Yes. Since 2019 NEET-UG is the single entrance exam for MBBS, BDS, BAMS, BHMS, BUMS, BSMS, B.V.Sc., and B.Sc. Nursing (15% AIQ) across India. There are no alternative entrances or management quotas without NEET.",
  },
  {
    q: "What is CUET-UG and is it mandatory?",
    a: "CUET-UG (Common University Entrance Test) is conducted by NTA every May–June. It is mandatory for admission to all 45 Central Universities (DU, JNU, BHU, JMI, AMU, etc.) and many state, deemed and private universities for non-professional UG courses.",
  },
  {
    q: "Can a Commerce or Arts student write the UPSC Civil Services exam?",
    a: "Absolutely. UPSC CSE is open to ANY graduate from any stream. In fact, Arts/Humanities backgrounds (Pol Sci, Geography, Public Admin, History) are very well-aligned with the UPSC syllabus.",
  },
  {
    q: "I want to join the Indian Armed Forces — what's the path from Class 10?",
    a: "Take Science PCM in Class 11–12 (mandatory for Air Force & Navy via NDA; Army NDA accepts any stream), then write the NDA exam (UPSC, twice a year) after Class 12. You must be 16.5–19.5 years and unmarried.",
  },
  {
    q: "How much do good colleges cost?",
    a: "Public colleges (IITs, NITs, AIIMS, IIMs, NLUs, IIMC, DU, JNU) are highly subsidised — ₹15k to ₹3 lakh per year. Top private colleges (BITS, VIT, Manipal, Ashoka, Jindal, NMIMS, Symbiosis) range from ₹3 lakh to ₹10 lakh per year. Always check fee waivers, scholarships and education loans.",
  },
  {
    q: "Is studying abroad after 12th better than in India?",
    a: "Not automatically. For undergraduate engineering/medicine/law, top Indian colleges (IITs, AIIMS, NLUs, IIMs IPM) offer world-class ROI at a fraction of the cost. Abroad UG makes sense for design, liberal arts, finance, or if you want global work mobility — but expect ₹40 lakh – ₹2 crore total cost.",
  },
  {
    q: "What if I don't crack any entrance exam?",
    a: "There are 1,000+ excellent open-admission courses: B.Com, BBA, BA Hons, B.Sc., BHM, BJMC, BFA, B.Pharm (in many states), diploma & ITI programs, online degrees from IGNOU/IITM BS, and skill courses via Skill India. A clear plan and strong execution matters more than the entrance you cleared.",
  },
];
